### ISSUE TITLE
Can not compile on apple silicon with python3.12

### ISSUE THREAD

**Issue by Eliott-Sarrey** [NickKarpowicz/LightwaveExplorer#37]
Dear Nick,

I tried to compile the code on an Apple Silicon Mac and had quite a hard time. It turns out that vcpkg relies on the distutils library, which is now outdated and no longer part of Python since version 3.12. One has to use a virtual environment with Python 3.11 or earlier, and it works.

It might be worth mentioning this in your documentation.

Thanks for your great software; I love it.

Cheers,
Eliott

**Comment by NickKarpowicz** [comment]
Hi Eliott! Thanks for pointing this out; I'll put it on my to-do list to update the Mac build process...

**Comment by NickKarpowicz** [comment]
Hi again!
This problem kind of fits into a set of problems that I've had using GTK cross-platform. It's just too much work to get it going properly on Windows and Mac. So I decided to switch to Qt.

I have a basically feature-complete version running in the QT_interface branch. I tried in on Mac just now, using homebrew for Qt so vcpkg is no longer needed. Qt in principle uses the native style unlike GTK, so it should eventually work more like a standard Mac application. At the moment everything is a few pixels in the wrong place, but that's fixable.

The build script for it is macMacAppQt.sh in that branch - if you can try the auto build from a fresh folder, it would be great to know if it works for you:
curl -s https://raw.githubusercontent.com/NickKarpowicz/LightwaveExplorer/QT_interface/Source/BuildResources/macAutoBuild.sh | zsh -s

Best wishes,
Nick
