### ISSUE TITLE
Crash when pressing save button or SVG button only in version 2024.2.1

### ISSUE THREAD

**Issue by FlorianLindinger** [NickKarpowicz/LightwaveExplorer#38]
Hey Nick,

When I press the save button or the SVG button on default settings in 2024.2.1, LWE crashes (closes window after freezing for a second). This only appears in 2024.2.1 but not 2024.2, so no deal breaker or hurry.

I have AMD Ryzen 7 5800H and NVIDIA GeForce RTX 3060 Laptop GPU on Windows 11.

-Flo (from Garching)

**Comment by FlorianLindinger** [comment]
Apparently there has been an update in the 2024.2.1 version. The crash happened in the April 3rd version and not anymore in the most recent version from April 23rd. So no problem.

**Comment by NickKarpowicz** [comment]
Hi Flo!
while you were writing, I was also writing :) I got a similar report about the crash bug (came from an outdated file in the packaging of the Windows version), and fixed it in the currently uploaded version.
Feel free to let me know when the next thing breaks though ;)
Best,
Nick
